// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiOEKNgYAUPtPoFEZgJkN_epXAR3Uy05k',
    appId: '1:357784097149:web:b714d7dba17939ef81bc14',
    messagingSenderId: '357784097149',
    projectId: 'linkd1-4e3a6',
    authDomain: 'linkd1-4e3a6.firebaseapp.com',
    databaseURL: 'https://linkd1-4e3a6-default-rtdb.firebaseio.com',
    storageBucket: 'linkd1-4e3a6.appspot.com',
    measurementId: 'G-YS0QR7BC24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr0Goe1o3-c57FkymlIsDcfj0KvOgU0ww',
    appId: '1:357784097149:android:8eb62b3c2becf28881bc14',
    messagingSenderId: '357784097149',
    projectId: 'linkd1-4e3a6',
    databaseURL: 'https://linkd1-4e3a6-default-rtdb.firebaseio.com',
    storageBucket: 'linkd1-4e3a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7qluaq2EKjY6ngOXq0BNl73lMxJksQPk',
    appId: '1:357784097149:ios:7afda45d632e2f9981bc14',
    messagingSenderId: '357784097149',
    projectId: 'linkd1-4e3a6',
    databaseURL: 'https://linkd1-4e3a6-default-rtdb.firebaseio.com',
    storageBucket: 'linkd1-4e3a6.appspot.com',
    androidClientId: '357784097149-ng28taj1uac7q15do6ibtp26nepgm2nf.apps.googleusercontent.com',
    iosClientId: '357784097149-sum2ltc99slmkqnf9671sc1r94n97egh.apps.googleusercontent.com',
    iosBundleId: 'com.trueworthfinance.trueworthfinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7qluaq2EKjY6ngOXq0BNl73lMxJksQPk',
    appId: '1:357784097149:ios:7afda45d632e2f9981bc14',
    messagingSenderId: '357784097149',
    projectId: 'linkd1-4e3a6',
    databaseURL: 'https://linkd1-4e3a6-default-rtdb.firebaseio.com',
    storageBucket: 'linkd1-4e3a6.appspot.com',
    androidClientId: '357784097149-ng28taj1uac7q15do6ibtp26nepgm2nf.apps.googleusercontent.com',
    iosClientId: '357784097149-sum2ltc99slmkqnf9671sc1r94n97egh.apps.googleusercontent.com',
    iosBundleId: 'com.trueworthfinance.trueworthfinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiOEKNgYAUPtPoFEZgJkN_epXAR3Uy05k',
    appId: '1:357784097149:web:d619c131aeb2fd8e81bc14',
    messagingSenderId: '357784097149',
    projectId: 'linkd1-4e3a6',
    authDomain: 'linkd1-4e3a6.firebaseapp.com',
    databaseURL: 'https://linkd1-4e3a6-default-rtdb.firebaseio.com',
    storageBucket: 'linkd1-4e3a6.appspot.com',
    measurementId: 'G-NN1ZLHGE04',
  );
}
